export const ROUTE_MANIFEST: Record<string, string[]> = {
    today: ['/today'],
    premarket: ['/premarket/journal', '/premarket/history'],
    options: ['/options', '/options/history'],
    accounting: [],
    dev: [
        '/api/dev/ops/next-action',
        '/api/dev/smoke/first-trade-unlock-check',
        '/api/dev/smoke/guided-first-trade',
        '/api/dev/system/routes',
        '/api/dev/ops/status',
        '/api/dev/health',
        '/api/dev/env-health',
        '/api/dev/schema-health',
        '/api/dev/risk-health',
        '/api/dev/provider-health',
        '/api/dev/broker-health',
        '/api/dev/broker-env',
        '/api/dev/agent-env',
        '/api/dev/clock/market',
        '/api/dev/deploy-hash',
        '/api/dev/premarket-diagnostics',
        '/api/dev/premarket-live-diagnostics',
        '/api/dev/premarket-verify',
        '/api/dev/purge-cache',
        '/api/dev/rules',
        '/api/dev/skills',
        '/api/dev/agent-prompt-meta',
        '/api/dev/smoke/paper-e2e',
        '/api/dev/smoke/paper-trade-lifecycle'
    ],
};
